### ISSUE TITLE
Unsure how to fix "cannot find type `Long` in module `super`" in my code

### ISSUE THREAD

**Issue by braincow** [graphql-rust/graphql-client#235]
I have a piece of code where I try to familiarize myself with graphql-client (and rust) and I end up hitting following compile error: https://github.com/braincow/hslstop-rt/issues/1

My suspicion is that I have something funky in the schema, but if someone with more experience could help me out with this?

**Comment by tomhoule** [comment]
I think you probably have a `Long` custom scalar defined in your schema. If `Long` is something like a float (for example) you can fix it by defining it (something like `type Long = f64;` next to your query struct - the thing you `#[derive(GraphQLQuery)]` on).

I just realized that we don't have a fix for this if you are using the CLI, I'll open a bug issue.

**Comment by tomhoule** [comment]
Similar example in the tests: https://github.com/graphql-rust/graphql-client/blob/master/graphql_client/tests/custom_scalars.rs

**Comment by braincow** [comment]
@tomhoule I used the cli to dump the schema. I was thinking along those same lines that it must be custom scalar or something else with the schema, but was unsure on how to fix it.

Code now compiles. Thank you. Closing this issue.

**Comment by LegNeato** [comment]
Is there some way we can make this a little less black magic / more discoverable?

**Comment by tomhoule** [comment]
I'll open an issue for it. I don't have a fundamentally better solution in mind because in the codegen code we don't know where scalars could be defined, but what we can do is:

- Make where the scalars live configurable (needed for the CLI).
- More importantly, document it better. I've been wanting to have a proper book for a long time, and it should definitely have a section for common type errors and how to debug them.

We could also think of a compeletely different system where the required scalars would have to be passed in a different way (through derive attributes for example) but it seems even less ergonomic to me.
