### ISSUE TITLE
Scalar types that begin with a lowercase letter

### ISSUE THREAD

**Issue by markcatley** [graphql-rust/graphql-client#254]
I am having issues with a scalar type in the graphql schema that beings with a lowercase letter as the type is not valid in rust. Is there any way to work around this?

**Comment by tomhoule** [comment]
Currently, the scalar type names are copied verbatim into the generated code. From just thinking about it a minute, I don't see what would break if we changed the case. So we should be able to fix this. I think it would be best implemented as part of #245 , otherwise the error messages are going to confuse users of the library.

**Comment by markcatley** [comment]
Thanks, @tomhoule. I managed to make a local change to allow me to continue. Once I made the change I noticed some more non-idiomatic rust generated by the schema. I have attached a PR of the changes I've made for discussion.

Do you think the changes I've made allow for idiomatic rust? If so, do you think the issues are related? If so, do you think my proposed solution is on the right track?

**Comment by markcatley** [comment]
Fantastic, thank you so much.

Also, thank you so much for the library!
